### ISSUE TITLE
Error during Casboundary

### ISSUE THREAD

**Issue by almutwerner** [BackofenLab/CRISPRloci#5]
Hello everyone!

I am running CRISPRloci in dna mode over a multi fasta and get the following error:
`
/work_beegfs/sunam157/CRISPRloci/CRISPRloci-1.0.0/Casboundary
Running Prodigal on input Fasta file.
Generating Genome DataFrame
Searching for potential signature proteins
Extracting potential regions.
Traceback (most recent call last):
  File "Casboundary.py", line 384, in <module>
    regions_fasta_file = extract_regions_sequences(proteins_fasta_file, regions_dataframes, args.output_dir)
  File "Casboundary.py", line 125, in extract_regions_sequences
    proteins_ids_regions = set.union(*regions_prot_ids)
TypeError: descriptor 'union' of 'set' object needs an argument

###################################################################################
###################################################################################

mkdir /work_dagan/sunam157/BGR_2013_2015/CRISPRloci/output/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0
res local folder /work_dagan/sunam157/BGR_2013_2015/CRISPRloci/output/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0
input file /work_dagan/sunam157/BGR_2013_2015/CRISPRloci/output/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0.fasta
Traceback (most recent call last):
  File "/work_beegfs/sunam157/CRISPRloci/CRISPRloci-1.0.0/CRISPRloci_standalone.py", line 1447, in <module>
    if len(os.listdir(dirname_cas + '/predictions/raw_cassettes/')) != 0:
FileNotFoundError: [Errno 2] No such file or directory: '/work_dagan/sunam157/BGR_2013_2015/CRISPRloci/output/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0/tmp/output-Casboundary/predictions/raw_cassettes/'
`

I briefly checked the output-Casboundary/hmmsearch_output_dir/Sig_HMM/ contents and didn't see any hits in the files. So I maybe, Casboundary was confused because there were no hits? 
I also ran it on the example data. There it completed that step without issues. I will add the failed fasta to this issue, so you can better trace the error.

[NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0.zip](https://github.com/BackofenLab/CRISPRloci/files/8561673/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0.zip)

**Comment by Alexander-Mitrofanov** [comment]
Yes it seems that the problem exactly with the Casboundary module.
It seems that the output is empty and therefore the error is occurring. 

Can I kindly ask you to provide the labled intervals for the given input sequence if you know that certain cassettes are missing?

**Comment by almutwerner** [comment]
Hello, thank you for your reply!
I have no idea whether the sequence contains anything or not. That was just my guess based on the HMM output. I will attach the whole output folder, maybe that is helpful to you.

[NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0.zip](https://github.com/BackofenLab/CRISPRloci/files/8989961/NODE_457_length_14276_cov_6173406__bin10_BGR2_DNA_150204_S0.zip)
